# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: Ensure TFTP Server is not installed (CIS)
  become: true
  ansible.builtin.package:
    name:
      - 'tftp-server'
    state: absent
